name: Renovate
on:
  workflow_dispatch:
  schedule:
      #@hourly	Run once an hour at the beginning of the hour -> 0 * * * *
      #@daily (or @midnight)	Run once a day at midnight -> 0 0 * * *
    - cron: '0 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.55.0
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
