name: Renovate
on:
  workflow_dispatch:
  schedule:
      #@hourly	Run once an hour at the beginning of the hour
    - cron: '0 * * * *'


jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.5.1
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}