name: Renovate
on:
  workflow_dispatch:
  schedule:
      #Run once a day at midnight
    - cron: '0 0 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.0
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
