name: Renovate
on:
  #TODO: rimuovere on.push.branches e abilitare on.schedule.cron
  push:
    branches: [ dev ]
  #schedule:
      #@daily (or @midnight) Run once a day at midnight
  #  - cron: '0 0 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup node
        uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458 # renovate: tag=v2.5.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Renovate
        uses: renovatebot/github-action@v26.21.7
        with:
          configurationFile: dist/src/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}